name: flutter_ebook_app
description: A Flutter app for eBooks

version: 1.0.3+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^8.1.4
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.3
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_icons:
    git: https://github.com/jibiel/flutter-icons
  flutter_riverpod: ^2.3.6
  flutter_spinkit: ^5.2.0
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.4
  path: ^1.8.2
  path_provider: ^2.0.3
  permission_handler: ^11.3.1
  sembast: ^3.4.5
  sembast_web: ^2.1.3
  share_plus: ^10.1.4
  xml2json: ^6.2.6
  epub_view: ^3.2.0
  shared_preferences: ^2.2.0


dependency_overrides:
  collection: ^1.17.2

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.3.4
  dart_code_metrics: ^5.7.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
